In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sps
import matplotlib.pyplot as plt
import datetime as dt
%matplotlib inline

In [2]:
%%time
mydata = pd.read_csv('all_vars.csv')

CPU times: user 6.19 s, sys: 634 ms, total: 6.83 s
Wall time: 7.01 s

In [3]:
mydata.dtypes

Recnum                 int64
Cardnum                int64
Date                  object
Merchnum              object
Merch description     object
Merch state           object
Merch zip              int64
Transtype             object
Amount               float64
Fraud                  int64
Rand                 float64
avg_card_1           float64
avg_card_7           float64
avg_card_14          float64
avg_card_30          float64
tot_card_1           float64
tot_card_7           float64
tot_card_14          float64
tot_card_30          float64
max_card_1           float64
max_card_7           float64
max_card_14          float64
max_card_30          float64
med_card_1           float64
med_card_7           float64
med_card_14          float64
med_card_30          float64
daa_card_1           float64
daa_card_7           float64
daa_card_14          float64
                      ...
med_cs_30            float64
daa_cs_1             float64
daa_cs_7             float64
daa_cs_14            float64
daa_cs_30            float64
dam_cs_1             float64
dam_cs_7             float64
dam_cs_14            float64
dam_cs_30            float64
qaa_cs_1             float64
qaa_cs_7             float64
qaa_cs_14            float64
qaa_cs_30            float64
qam_cs_1             float64
qam_cs_7             float64
qam_cs_14            float64
qam_cs_30            float64
qat_cs_1             float64
qat_cs_7             float64
qat_cs_14            float64
qat_cs_30            float64
qamed_cs_1           float64
qamed_cs_7           float64
qamed_cs_14          float64
qamed_cs_30          float64
ntr_cs_1               int64
ntr_cs_7               int64
ntr_cs_14              int64
ntr_cs_30              int64
cs_diff               object
Length: 242, dtype: object

In [4]:
mydata.head(10)

,Recnum,Cardnum,Date,Merchnum,Merch description,Merch state,Merch zip,Transtype,Amount,Fraud,...,qat_cs_30,qamed_cs_1,qamed_cs_7,qamed_cs_14,qamed_cs_30,ntr_cs_1,ntr_cs_7,ntr_cs_14,ntr_cs_30,cs_diff
0,1,5142190439,1/1/10,5.50901E+12,FEDEX SHP 12/23/09 AB#,TN,38118,P,3.62,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
1,2,5142183973,1/1/10,61003026333,SERVICE MERCHANDISE #81,MA,1803,P,31.42,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
2,3,5142131721,1/1/10,4.50308E+12,OFFICE DEPOT #191,MD,20706,P,178.49,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
3,4,5142148452,1/1/10,5.50901E+12,FEDEX SHP 12/28/09 AB#,TN,38118,P,3.62,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
4,5,5142190439,1/1/10,5.50901E+12,FEDEX SHP 12/23/09 AB#,TN,38118,P,3.62,0,...,0.500000,1.0,1.0,1.0,1.0,2,2,2,2,0 days 00:00:00.000000000
5,6,5142149874,1/1/10,5.50901E+12,FEDEX SHP 12/22/09 AB#,TN,38118,P,3.67,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
6,7,5142189277,1/1/10,5.50901E+12,FEDEX SHP 12/28/09 AB#,TN,38118,P,3.62,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
7,8,5142191182,1/1/10,6.09821E+12,MIAMI COMPUTER SUPPLY,OH,45429,P,230.32,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
8,9,5142258629,1/1/10,6.02609E+11,FISHER SCI ATL,GA,30091,P,62.11,0,...,1.000000,1.0,1.0,1.0,1.0,1,1,1,1,0 days 00:00:00.000000000
9,10,5142190439,1/1/10,5.50901E+12,FEDEX SHP 12/23/09 AB#,TN,38118,P,3.62,0,...,0.333333,1.0,1.0,1.0,1.0,3,3,3,3,0 days 00:00:00.000000000

In [5]:
mydata['Date'] = pd.to_datetime(mydata['Date'])
mydata.dtypes

Recnum                        int64
Cardnum                       int64
Date                 datetime64[ns]
Merchnum                     object
Merch description            object
Merch state                  object
Merch zip                     int64
Transtype                    object
Amount                      float64
Fraud                         int64
Rand                        float64
avg_card_1                  float64
avg_card_7                  float64
avg_card_14                 float64
avg_card_30                 float64
tot_card_1                  float64
tot_card_7                  float64
tot_card_14                 float64
tot_card_30                 float64
max_card_1                  float64
max_card_7                  float64
max_card_14                 float64
max_card_30                 float64
med_card_1                  float64
med_card_7                  float64
med_card_14                 float64
med_card_30                 float64
daa_card_1                  float64
daa_card_7                  float64
daa_card_14                 float64
                          ...
med_cs_30                   float64
daa_cs_1                    float64
daa_cs_7                    float64
daa_cs_14                   float64
daa_cs_30                   float64
dam_cs_1                    float64
dam_cs_7                    float64
dam_cs_14                   float64
dam_cs_30                   float64
qaa_cs_1                    float64
qaa_cs_7                    float64
qaa_cs_14                   float64
qaa_cs_30                   float64
qam_cs_1                    float64
qam_cs_7                    float64
qam_cs_14                   float64
qam_cs_30                   float64
qat_cs_1                    float64
qat_cs_7                    float64
qat_cs_14                   float64
qat_cs_30                   float64
qamed_cs_1                  float64
qamed_cs_7                  float64
qamed_cs_14                 float64
qamed_cs_30                 float64
ntr_cs_1                      int64
ntr_cs_7                      int64
ntr_cs_14                     int64
ntr_cs_30                     int64
cs_diff                      object
Length: 242, dtype: object

In [6]:
# drop the OOT data
mydata = mydata[mydata['Date'] <= '2010-11-01']
mydata.shape

(84161, 242)

In [7]:
mydata.drop(['Date','Recnum','Cardnum','Merchnum','Merch description','Merch state','Merch zip','Transtype','Amount'], axis=1, inplace=True)
mydata.shape

(84161, 233)

In [8]:
mydata.describe(include = 'all')

,Fraud,Rand,avg_card_1,avg_card_7,avg_card_14,avg_card_30,tot_card_1,tot_card_7,tot_card_14,tot_card_30,...,qat_cs_30,qamed_cs_1,qamed_cs_7,qamed_cs_14,qamed_cs_30,ntr_cs_1,ntr_cs_7,ntr_cs_14,ntr_cs_30,cs_diff
count,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,...,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161.000000,84161
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:00.000000000
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16341
mean,0.010456,0.500417,396.296082,400.099109,400.561436,398.700169,758.037462,2167.969078,3589.972844,6606.753981,...,0.486934,1.049829,1.209253,1.360016,1.534308,2.197407,4.485664,6.426801,10.364741,NaN
std,0.101720,0.289046,734.635864,583.649316,543.690304,493.718695,3634.885243,7169.433439,9417.783923,14660.505211,...,0.411375,1.968903,3.941463,5.508835,6.506711,6.090710,16.400142,20.283587,30.299455,NaN
min,0.000000,0.000003,0.010000,0.140000,0.140000,0.170000,0.010000,0.140000,0.140000,0.170000,...,0.000007,0.000090,0.000090,0.000090,0.000068,1.000000,1.000000,1.000000,1.000000,NaN
25%,0.000000,0.250135,40.770000,88.425000,114.766667,146.122000,59.000000,247.840000,512.150000,1135.940000,...,0.074459,1.000000,1.000000,1.000000,0.958333,1.000000,1.000000,1.000000,1.000000,NaN
50%,0.000000,0.500976,160.000000,244.885000,277.157500,304.296786,219.000000,864.300000,1605.930000,3213.150000,...,0.369925,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,3.000000,NaN
75%,0.000000,0.751225,455.505000,503.477500,506.264286,499.565000,685.250000,2336.110000,3875.970000,7296.610000,...,1.000000,1.000000,1.000000,1.000000,1.033856,1.000000,3.000000,4.000000,6.000000,NaN
max,1.000000,0.999991,28392.840000,25500.000000,25500.000000,25500.000000,218301.830000,312616.060000,313995.060000,350158.290000,...,1.000000,390.743707,496.031746,543.596730,607.785888,146.000000,353.000000,380.000000,424.000000,NaN

In [9]:
mydata.count()

Fraud          84161
Rand           84161
avg_card_1     84161
avg_card_7     84161
avg_card_14    84161
avg_card_30    84161
tot_card_1     84161
tot_card_7     84161
tot_card_14    84161
tot_card_30    84161
max_card_1     84161
max_card_7     84161
max_card_14    84161
max_card_30    84161
med_card_1     84161
med_card_7     84161
med_card_14    84161
med_card_30    84161
daa_card_1     84161
daa_card_7     84161
daa_card_14    84161
daa_card_30    84161
dam_card_1     84161
dam_card_7     84161
dam_card_14    84161
dam_card_30    84161
qaa_card_1     84161
qaa_card_7     84161
qaa_card_14    84161
qaa_card_30    84161
               ...
med_cs_30      84161
daa_cs_1       84161
daa_cs_7       84161
daa_cs_14      84161
daa_cs_30      84161
dam_cs_1       84161
dam_cs_7       84161
dam_cs_14      84161
dam_cs_30      84161
qaa_cs_1       84161
qaa_cs_7       84161
qaa_cs_14      84161
qaa_cs_30      84161
qam_cs_1       84161
qam_cs_7       84161
qam_cs_14      84161
qam_cs_30      84161
qat_cs_1       84161
qat_cs_7       84161
qat_cs_14      84161
qat_cs_30      84161
qamed_cs_1     84161
qamed_cs_7     84161
qamed_cs_14    84161
qamed_cs_30    84161
ntr_cs_1       84161
ntr_cs_7       84161
ntr_cs_14      84161
ntr_cs_30      84161
cs_diff        84161
Length: 233, dtype: int64

In [10]:
mydata.max()

Fraud                                   1
Rand                             0.999991
avg_card_1                        28392.8
avg_card_7                          25500
avg_card_14                         25500
avg_card_30                         25500
tot_card_1                         218302
tot_card_7                         312616
tot_card_14                        313995
tot_card_30                        350158
max_card_1                          47900
max_card_7                          47900
max_card_14                         47900
max_card_30                         47900
med_card_1                        28392.8
med_card_7                          25500
med_card_14                         25500
med_card_30                         25500
daa_card_1                          22400
daa_card_7                        24044.3
daa_card_14                       24044.3
daa_card_30                       26717.9
dam_card_1                        28367.2
dam_card_7                        28599.5
dam_card_14                       28599.5
dam_card_30                       28599.5
qaa_card_1                        23.7912
qaa_card_7                        59.4811
qaa_card_14                       71.3322
qaa_card_30                       137.987
                          ...
med_cs_30                         28392.8
daa_cs_1                            22400
daa_cs_7                            22400
daa_cs_14                           22400
daa_cs_30                           22400
dam_cs_1                          28367.2
dam_cs_7                          28367.2
dam_cs_14                         28367.2
dam_cs_30                         28367.2
qaa_cs_1                          20.2425
qaa_cs_7                           28.227
qaa_cs_14                         22.2806
qaa_cs_30                         33.8256
qam_cs_1                                1
qam_cs_7                                1
qam_cs_14                               1
qam_cs_30                               1
qat_cs_1                                1
qat_cs_7                                1
qat_cs_14                               1
qat_cs_30                               1
qamed_cs_1                        390.744
qamed_cs_7                        496.032
qamed_cs_14                       543.597
qamed_cs_30                       607.786
ntr_cs_1                              146
ntr_cs_7                              353
ntr_cs_14                             380
ntr_cs_30                             424
cs_diff        99 days 00:00:00.000000000
Length: 233, dtype: object

In [11]:
# variables = list(mydata.drop(['Fraud'],axis=1).columns)
variables = list(mydata.columns)
print(variables)

['Fraud', 'Rand', 'avg_card_1', 'avg_card_7', 'avg_card_14', 'avg_card_30', 'tot_card_1', 'tot_card_7', 'tot_card_14', 'tot_card_30', 'max_card_1', 'max_card_7', 'max_card_14', 'max_card_30', 'med_card_1', 'med_card_7', 'med_card_14', 'med_card_30', 'daa_card_1', 'daa_card_7', 'daa_card_14', 'daa_card_30', 'dam_card_1', 'dam_card_7', 'dam_card_14', 'dam_card_30', 'qaa_card_1', 'qaa_card_7', 'qaa_card_14', 'qaa_card_30', 'qat_card_1', 'qat_card_7', 'qat_card_14', 'qat_card_30', 'qam_card_1', 'qam_card_7', 'qam_card_14', 'qam_card_30', 'qamed_card_1', 'qamed_card_7', 'qamed_card_14', 'qamed_card_30', 'ntr_cardnum_1', 'ntr_cardnum_7', 'ntr_cardnum_14', 'ntr_cardnum_30', 'v_card_7', 'v_card_14', 'v_card_30', 'card_diff', 'avg_merch_1', 'avg_merch_7', 'avg_merch_14', 'avg_merch_30', 'tot_merch_1', 'tot_merch_7', 'tot_merch_14', 'tot_merch_30', 'med_merch_1', 'med_merch_7', 'med_merch_14', 'med_merch_30', 'max_merch_1', 'max_merch_7', 'max_merch_14', 'max_merch_30', 'daa_merch_1', 'daa_merch_7', 'daa_merch_14', 'daa_merch_30', 'dam_merch_1', 'dam_merch_7', 'dam_merch_14', 'dam_merch_30', 'qaa_merch_1', 'qaa_merch_7', 'qaa_merch_14', 'qaa_merch_30', 'qat_merch_1', 'qat_merch_7', 'qat_merch_14', 'qat_merch_30', 'qam_merch_1', 'qam_merch_7', 'qam_merch_14', 'qam_merch_30', 'qamed_merch_1', 'qamed_merch_7', 'qamed_merch_14', 'qamed_merch_30', 'ntr_merch_1', 'ntr_merch_7', 'ntr_merch_14', 'ntr_merch_30', 'v_merch_7', 'v_merch_14', 'v_merch_30', 'merch_diff', 'avg_cm_1', 'avg_cm_7', 'avg_cm_14', 'avg_cm_30', 'tot_cm_1', 'tot_cm_7', 'tot_cm_14', 'tot_cm_30', 'max_cm_1', 'max_cm_7', 'max_cm_14', 'max_cm_30', 'med_cm_1', 'med_cm_7', 'med_cm_14', 'med_cm_30', 'daa_cm_1', 'daa_cm_7', 'daa_cm_14', 'daa_cm_30', 'dam_cm_1', 'dam_cm_7', 'dam_cm_14', 'dam_cm_30', 'qaa_cm_1', 'qaa_cm_7', 'qaa_cm_14', 'qaa_cm_30', 'qam_cm_1', 'qam_cm_7', 'qam_cm_14', 'qam_cm_30', 'qat_cm_1', 'qat_cm_7', 'qat_cm_14', 'qat_cm_30', 'qamed_cm_1', 'qamed_cm_7', 'qamed_cm_14', 'qamed_cm_30', 'ntr_cm_1', 'ntr_cm_7', 'ntr_cm_14', 'ntr_cm_30', 'cm_diff', 'avg_cz_1', 'avg_cz_7', 'avg_cz_14', 'avg_cz_30', 'tot_cz_1', 'tot_cz_7', 'tot_cz_14', 'tot_cz_30', 'max_cz_1', 'max_cz_7', 'max_cz_14', 'max_cz_30', 'med_cz_1', 'med_cz_7', 'med_cz_14', 'med_cz_30', 'daa_cz_1', 'daa_cz_7', 'daa_cz_14', 'daa_cz_30', 'dam_cz_1', 'dam_cz_7', 'dam_cz_14', 'dam_cz_30', 'qaa_cz_1', 'qaa_cz_7', 'qaa_cz_14', 'qaa_cz_30', 'qam_cz_1', 'qam_cz_7', 'qam_cz_14', 'qam_cz_30', 'qat_cz_1', 'qat_cz_7', 'qat_cz_14', 'qat_cz_30', 'qamed_cz_1', 'qamed_cz_7', 'qamed_cz_14', 'qamed_cz_30', 'ntr_cz_1', 'ntr_cz_7', 'ntr_cz_14', 'ntr_cz_30', 'cz_diff', 'avg_cs_1', 'avg_cs_7', 'avg_cs_14', 'avg_cs_30', 'tot_cs_1', 'tot_cs_7', 'tot_cs_14', 'tot_cs_30', 'max_cs_1', 'max_cs_7', 'max_cs_14', 'max_cs_30', 'med_cs_1', 'med_cs_7', 'med_cs_14', 'med_cs_30', 'daa_cs_1', 'daa_cs_7', 'daa_cs_14', 'daa_cs_30', 'dam_cs_1', 'dam_cs_7', 'dam_cs_14', 'dam_cs_30', 'qaa_cs_1', 'qaa_cs_7', 'qaa_cs_14', 'qaa_cs_30', 'qam_cs_1', 'qam_cs_7', 'qam_cs_14', 'qam_cs_30', 'qat_cs_1', 'qat_cs_7', 'qat_cs_14', 'qat_cs_30', 'qamed_cs_1', 'qamed_cs_7', 'qamed_cs_14', 'qamed_cs_30', 'ntr_cs_1', 'ntr_cs_7', 'ntr_cs_14', 'ntr_cs_30', 'cs_diff']

In [12]:
nvars = len(variables)
print(nvars)

233

In [13]:
print(mydata.columns)

Index(['Fraud', 'Rand', 'avg_card_1', 'avg_card_7', 'avg_card_14',
       'avg_card_30', 'tot_card_1', 'tot_card_7', 'tot_card_14', 'tot_card_30',
       ...
       'qat_cs_30', 'qamed_cs_1', 'qamed_cs_7', 'qamed_cs_14', 'qamed_cs_30',
       'ntr_cs_1', 'ntr_cs_7', 'ntr_cs_14', 'ntr_cs_30', 'cs_diff'],
      dtype='object', length=233)

In [14]:
goods = mydata[mydata['Fraud'] == 0]
goods.shape

(83281, 233)

In [15]:
bads = mydata[mydata['Fraud'] == 1]
bads.shape

(880, 233)

In [16]:
numgoods = len(goods)
numbads = len(bads)

In [17]:
KS_FDR = pd.DataFrame(np.zeros((nvars+2,3)))
i = 0
for column in mydata:
#     print(i, column)
    KS_FDR.loc[i, 0] = column
    i= i+1

In [18]:
KS_FDR.columns = ['field', 'ks', 'FDR']

In [19]:
%%time
# this is the KS routine in scipy
j = 0
for column in mydata:
    (ks, pval) = sps.ks_2samp(goods[column],bads[column])
    KS_FDR.loc[j, 'ks'] = ks
    j = j+1

CPU times: user 4.12 s, sys: 37 ms, total: 4.16 s
Wall time: 4.19 s

In [20]:
# %%time
# this is my own KS calculation to check the scipy one, but it only works on variables that are counts (integers)
# make two separate normalized distributions, make the cumulative distributions, subtract the cumulatives, find the max
# j = 0
# for column in mydata:
#     variable = column
#     variable_max = mydata[variable].max()
#     x = pd.DataFrame(goods[variable].value_counts().sort_index())
#     x['index'] = x.index
#     y = pd.DataFrame(bads[variable].value_counts().sort_index())
#     y['index'] = y.index
#     dist1 = np.zeros(variable_max + 1)
#     dist2 = np.zeros(variable_max + 1)
#     dif = np.zeros(variable_max + 1)
#     for i in range(variable_max + 1):
#         if i in x['index']:
#             dist1[i] = x.loc[i,variable]
#         if i in y['index']:
#             dist2[i] = y.loc[i, variable]
#     dist1 = dist1 / numgoods
#     dist2 = dist2 / numbads 
#     dif[0] = dist1[0] - dist2[0]
#     for i in range(1,variable_max + 1):
#         dist1[i] = dist1[i-1] + dist1[i]
#         dist2[i] = dist2[i-1] + dist2[i]
#         dif[i] = dist1[i] - dist2[i]
        
#     ksmax = dif.max() * 100
#     print(j, column,ksmax)
#     KS_FDR.loc[j, 'ks'] = ksmax
#     j = j +1

In [21]:
%%time
# this calculates the FDR @ 3% for all the variables
# note that you have to calculate it two ways since you don't know which way the bads are ranked by each variable
# calculate it both ways, then take the max
topRows = int(round(len(mydata)*0.03))
j = 0
for column in mydata:
    temp1 = mydata.sort_values(column,ascending=False).head(topRows)
    temp2 = mydata.sort_values(column,ascending=True).head(topRows)
    needed1 = temp1.loc[:,'Fraud']
    needed2 = temp2.loc[:,'Fraud']
    FDR1 = sum(needed1)/numbads
    FDR2 = sum(needed2)/numbads
    FDRate = np.maximum(FDR1,FDR2)
#     print(column, FDR1, FDR2, FDRate)
    KS_FDR.loc[j, 'FDR'] = FDRate
    j = j + 1

CPU times: user 1min 12s, sys: 38.4 s, total: 1min 50s
Wall time: 1min 52s

In [22]:
KS_FDR.sort_values(by=['ks'], ascending=False, inplace=True)
KS_FDR.to_csv('Feature selection filter sorted by KS.csv', index = False)

In [23]:
KS_FDR.sort_values(by=['FDR'], ascending=False, inplace=True)
KS_FDR.to_csv('Feature selection filter sorted by FDR.csv', index = False)